### ISSUE TITLE
Failing to fetchCart

### ISSUE THREAD

**Issue by gmldog76** [Shopify/js-buy-sdk#336] opened 2017-04-07 04:21 UTC
I'm using js-buy-sdk as a node package(0.7.1), and attempting to fetch a cart and update it. Unfortunately, whenever I attempt to get a cart I recently created it cannot be found. 

I run the my application with a set of parameters that causes it to create a cart and return the ID (and checkoutUrl) upon success. After that, I run the application again including the fresh cart_id and a different quantity to update the with cart. This is when I run into the issue.

I stepped through the code and found that it is trying to pull the cart out of the localStorageAdapter's Store's cache without making a network call to populate the cache.

Is fetchCart designed to only be valid for carts created within the same execution of the application? 
Is there something special I can do to force it to populate the cache prior to fetchCart?

**Comment by doublerebel** [comment] 2017-06-29 14:20
This would be a dupe of #178, #301, and #312 -- except that those 3 issues were incorrectly closed.  This is a real problem and these issues should be left open until resolved -- meaning it fully passes tests in Node as in #131 or similar.

Both the documentation and the [(outdated) node-js-buy example](https://github.com/Shopify/storefront-api-examples/blob/master/node-js-buy/src/app.js#L28) demonstrate `fetchCart` as if it can be used serverside, but all these issues show that has never worked -- meaning the example I'm following probably never worked either.

The typical solution is to support npm package **express-session**, then the cart will work with existing session settings and the developer can handle it further.

At the very least please add to docs that this does not work in Node!   Many thanks.

**Comment by swalkinshaw** [comment] 2017-07-04 16:02
Just to clear up a few things:

**JS Buy SDK v0.x**
Carts are managed in localStorage and not persisted to our API. As mentioned, this doesn't work seamlessly server-side with Node.js. You have to do more manual work to persist the Cart. It's not something we documented which unfortunately leads to this confusion.

It's also something we likely won't be fixing because of the new Storefront API and v1.x.

**JS Buy SDK v1.x**
This version is currently in alpha and will be officially released as the stable version soon.

Carts are now **Checkouts** as documented in the [Migration guide](https://github.com/Shopify/js-buy-sdk/blob/v1.0alpha/docs/MIGRATION_GUIDE.md). They are persisted to Shopify's API which makes them a lot easier to work with and require less manual work. But it's still up to you to store the checkout ID for later use.

All of the examples in https://github.com/Shopify/storefront-api-examples are using the newer Storefront API which is what v1.x is built on.

> While I'm at it, it's confusing that this repo has a completely different name from its npm package.

I know 😔 . There's no real way to rename packages on npm though. We'd have to deprecate the package and create a new one.

>  I attempted to clone and run tests on the @alpha branch to determine how functional it is, but since it requires native compilation and a yarn setup I am not yet able to run the tests.

Maybe you could create a separate issue with details of what you're running into?

**Comment by swalkinshaw** [comment] 2017-07-04 16:05
@gmldog76 back to your original issue. I think there's two options:

1. We recommend switching to v1.x alpha. Despite being marked as "alpha", it's still our recommended version to use now since it offers a lot more functionality and it's using our officially documented Storefront API.
2. You might be able to write your own adapter which is API compatible with [LocalStoreAdapter](https://github.com/Shopify/js-buy-sdk/blob/df0b30592e58177aa7ca1e981ea3c044f6ccfe8c/src/adapters/local-storage-adapter.js). Then after you create a client instance, you can override `adapters` (I think):

```js
var shopClient = ShopifyBuy.buildClient({
  accessToken: 'your-access-token',
  domain: 'your-shop-subdomain.myshopify.com',
  appId: '6'
});

shopClient.adapters = {
  products: ListingsAdapter,
  collections: ListingsAdapter,
  carts: MyCustomAdapter,
  references: LocalStorageAdapter
}
```

**Comment by gmldog76** [comment] 2017-07-05 17:57
@swalkinshaw,
Thank you for the feedback on this issue. I ended up making a new cart each time it changes. It is an ugly solution, but I'm too lazy to go back and change it since it has been working for a couple months now.

As a result, I won't be testing these solutions in the foreseeable future. However, I'm sure they will be of use to others facing this issue.

Once again, thank you for your time.

**Comment by doublerebel** [comment] 2017-07-10 08:22
@swalkinshaw Thanks, it does help to know for sure that I am supposed to keep track of the checkout ID myself.

I am able to run the node tests, turns out they work fine without whichever module needed native compilation -- which is how I noticed #385.

I ended up creating my own express middleware so that I could have #98 and #304 (and partway through #384).  I'm happy to donate the code, I don't know if a PR goes best in this lib or elsewhere.  I have a Webhook HMAC verification middleware with it too, since the [ones in npm](https://www.npmjs.com/search?q=shopify+webhook) are [outdated](https://github.com/GAWMiners/shopify-validate/issues/1).

**Comment by swalkinshaw** [comment] 2017-07-10 14:12
I'd say a separate repo for now. Maybe we can revisit that once v1 alpha becomes the stable release.

**Comment by goldenlocks52** [comment] 2019-04-09 17:28
Hi Scott, we have are having an issue finding the right way for our "add to cart" function. We have an API to our clients stores and they use our chat software. Shoppers push our add to cart button and we update their cart. We can not get the SDK to take that "event" and update the shopify store. There must be a way to do this but we've been hitting walls. 

Can you shine a light into a path to "add to cart"?

**Comment by rebeccajfriedman** [comment] 2019-04-12 13:43
Closing this ticket as the most recent version of JS Buy SDK is 2.2.1 and we can no longer provide support on legacy versions.

@goldenlocks52 The [README](https://github.com/Shopify/js-buy-sdk#creating-a-checkout) has some documentation on creating carts (we call them checkouts).

**Closed by rebeccajfriedman** 2019-04-12 13:43 UTC
