### ISSUE TITLE
Uncaught (in promise) when calling client.product.fetchAll()

### ISSUE THREAD

**Issue by baptistebriel** [Shopify/js-buy-sdk#597] opened 2018-11-14 22:59 UTC
**Describe the bug**
I cannot fetchAll products from a simple `buildClient`, the exact same code as showned in the getting started demos.

<img width="818" alt="screen shot 2018-11-14 at 2 52 40 pm" src="https://user-images.githubusercontent.com/2464663/48517993-fd3a8800-e81c-11e8-8401-e6039b520042.png">

**To Reproduce**
```javascript
const client = Client.buildClient({
  domain: 'subdomain.myshopify.com',
  storefrontAccessToken: 'access-token'
});

client.product.fetchAll().then((products) => {
  // Do something with the products
  console.log(products);
});
```

**Expected behavior**
Should get a JS object list of all the products listed on the Shopify store.

**Environment (please complete the following information):**
 - All
 - Tested on Chrome
 - SDK Version 1.10.0

**Additional context**

Weird thing is, if I try to access the .json file using `https://user:pass@subdomain.myshopify.com/admin/products.json` from the StoreFront API, I do get a list of products. Seems like the issue I'm having is only with the Shopify Buy SDK.
Is there something I'm missing here? Thanks a lot for the help.

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by mikkoh** [comment] 2018-11-15 21:41
@rebeccajfriedman I looked into this issue. I'm able to reproduce this on my test shop if I disable the `Read Product Tags` permission.

<img width="598" alt="screen shot 2018-11-15 at 4 33 58 pm" src="https://user-images.githubusercontent.com/496903/48583224-8d97cc00-e8f4-11e8-8f87-4a8654882e0d.png">

@baptistebriel try it out. See if checking/allowing this permission helps. You can temporarily enable it. If there's a reason why you don't want this permission enabled your best option might be to wait for a fix.

**Comment by baptistebriel** [comment] 2018-11-16 04:19
That fixed the access denied issue! Thanks a lot!

**Comment by igghera** [comment] 2018-11-16 17:10
Hi @mikkoh, do you think removing `tags` from the Product fragment makes sense? 

That's how I solved the problem before seeing your reply on this issue. And if the permissions to read tags are disabled by default in the Storefront API, every developer that tries out this SDK will step into this issue, right?

Happy to contribute and do it myself, but only if that's a reasonable solution to this issue.

**Comment by rebeccajfriedman** [comment] 2018-11-16 20:30
@igghera feel free to make a PR to remove `tags` from the fragment.  You are correct that since the permission is intentionally not checked by default, we should not include the field in the default fragment.

We are planning to release a major version of JS Buy SDK to [remove deprecated fields](https://github.com/Shopify/js-buy-sdk/pull/596), and we would love to include this.

**Comment by arobbins** [comment] 2018-11-16 20:36
This would be a fantastic fix. Most of my users are currently running into this issue :)

**Comment by igghera** [comment] 2018-11-17 00:33
@rebeccajfriedman @arobbins done

**Comment by baptistebriel** [comment] 2018-11-19 20:55
Feel free to close this issue whenever the PR gets merged. Thanks, everyone!

**Comment by rebeccajfriedman** [comment] 2018-11-20 14:14
FYI that we are planning to release this as part of a new version on November 27. Thanks everyone!

**Comment by rebeccajfriedman** [comment] 2018-11-28 13:51
@priyankafet This change was released in version `1.11.0`. In the immediate term, you can just lock to version `1.10.0` and you will have tags back. We are working on a way to allow more flexibility with the queries, but you can also patch the SDK by writing your own product fragment and passing it through your own method.

**Comment by priyankafet** [comment] 2018-11-29 06:11
We are using the older version but still not getting tags in return.

**Comment by priyankafet** [comment] 2018-11-29 10:16
Can you pls send us CDN URL to access the 1.10.0? We were using below URL earlier:

https://sdks.shopifycdn.com/js-buy-sdk/v1/latest/index.umd.min.js

**Comment by StefanSlehta** [comment] 2018-11-29 12:05
Hi @priyankafet sorry for the hassle. Here's a link to 1.10.0
https://sdks.shopifycdn.com/js-buy-sdk/1.10.0/index.umd.min.js

**Closed** 2019-05-06 17:31 UTC
Labels: bug
