### ISSUE TITLE
removeLineItems empties the whole checkout

### ISSUE THREAD

**Issue by silvainSayduck** [Shopify/js-buy-sdk#721] opened 2019-10-29 08:26 UTC
Using `client.checkout.removeLineItems(checkoutId, [lineItemId])` empties the whole checkout (ie. the returned `checkout.lineItems.length === 0`).

For good measure, I tried passing`[productId]` (since that's what is in fact wrongly used in the examples, even though it's logically written to use a `lineItemId`) and that logically crashes.
I also tried passing `[variantId]` and that also empties the whole checkout.

Finally, using `client.checkout.removeLineItems(checkoutId, [])` logically does nothing, and any other form of attempts `[{ id: lineItemId }]`, `[{ id: lineItemId, quantity: 0 }]`, ... also logically crashes.

Am I doing something wrong, or can this issue be reproduced?

I'm using `"shopify-buy": "2.8.0",`

**Comment by rebeccajfriedman** [comment] 2019-12-04 17:13
Hi @silvainSayduck - I am unable to reproduce the issue that you mentioned. I added two line items to a checkout, and then removed one of them using their ID.

If you are still experiencing this issue, can you please provide all your code?

**Comment by rebeccajfriedman** [comment] 2019-12-13 21:17
I'm going to close this issue. Please reopen it if you are still experiencing a problem.

**Closed by rebeccajfriedman** 2019-12-13 21:17 UTC
