### ISSUE TITLE
[1.0alpha] checkout 'Return to cart' link

### ISSUE THREAD

**Issue by formatlos** [Shopify/js-buy-sdk#442] opened 2017-11-04 10:44 UTC
I'd like to have an 'Return to cart' Link on the checkout page like in the normal checkout flow. Is there some sort of query param to enable that?

**Comment by rebeccajfriedman** [comment] 2019-09-27 15:56
Closing this as dupe of https://github.com/Shopify/js-buy-sdk/issues/179

**Closed by rebeccajfriedman** 2019-09-27 15:56 UTC
