### ISSUE TITLE
Schema Updated, but graph-ql-client is getting no data (Metafields)

### ISSUE THREAD

**Issue by philippsiegmund** [Shopify/js-buy-sdk#683] opened 2019-07-01 12:10 UTC
**Describe the bug**
I have seen the schema.json gut updated with #671 and Metafields are available.
When I try to get "metafields" with client.product or client.graphQLClient.query()

I always get "No field of name "metafields" found on type "Product" in schema"

**To Reproduce**
Steps to reproduce the behaviour:

```

// Build a custom products query using the unoptimized version of the SDK
    const productsQuery = client.graphQLClient.query((root) => {
      root.addConnection('products', {args: {first: 10}}, (product) => {
        product.add('id');
        product.addConnection('metafields', {args: {first: 5}}, (meta) => {
          meta.add('description')
        })
      });
    });

// Call the send method with the custom products query
    client.graphQLClient.send(metaQuery).then(({model, data}) => {
      // Do something with the products
      console.log(model);
    });
```

**Expected behavior**
Get the products metafields.

**Environment (please complete the following information):**
 - OSX (10.14.5)
 - Chrome (latest)
 - js-buy-sdk 2.5.0

**Additional context**
I have seen that even if the js-buy-sdk has metafields in the schema the imported graphl-ql-client has no metafields at schema.json

I have also tried to copy the ProductFragment and create my own query, but the is rejected by graphQLclient.send(query).

Thanks for any help!

**Comment by philippsiegmund** [comment] 2019-07-02 09:20
As stated on the [Metafield API Guides](https://help.shopify.com/en/api/guides/metafields/storefront-api-metafields#expose-metafields-to-the-storefront-api):

> "By default, the Storefront API can't read metafields. To expose specific metafields to the Storefront API, you need to use the GraphQL Admin API to whitelist them."

So I'm going to discard the js-buy-sdk implementation and use ApolloClient with full Auth and GraphQL Admin API. 

IMHO this shouldn't be necessary for some Metafields

**Comment by rebeccajfriedman** [comment] 2019-07-02 13:19
I'll close this issue out, as you seem to have found a workaround for your use case. My recommendation is still to follow the metafields guide, as it will give you control over which metafields are publicly accessible, but you can do whatever you are most comfortable with.

**Closed by rebeccajfriedman** 2019-07-02 13:19 UTC

**Comment by philippsiegmund** [comment] 2019-07-04 09:59
Honestly, I had to find a workaround because the SDK is not working...

**Comment by tylermcrobert** [comment] 2020-01-05 21:33
I'm having the same issue. Any update on this?

**Comment by rebeccajfriedman** [comment] 2020-01-06 16:08
@tylermcrobert Can you please explain what isn't working?

Following the [Metafields guide](https://help.shopify.com/en/api/guides/metafields/storefront-api-metafields#expose-metafields-to-the-storefront-api) to whitelist metafields to the Storefront API, and then using the custom query above, I am able to fetch metafields.

**Comment by tylermcrobert** [comment] 2020-01-06 18:19
@rebeccajfriedman I get the error "No field of name "metafields" found on type "Product" in schema". I had to switch to the storefront API where the whitelisted metafields _do_ show up.

**Comment by rebeccajfriedman** [comment] 2020-01-06 18:36
> I get the error "No field of name "metafields" found on type "Product" in schema".

What version of the schema are you using?

**Comment by tylermcrobert** [comment] 2020-01-06 18:56
I believe I was using the 2019-07 version. Is that what you're asking?

**Comment by rebeccajfriedman** [comment] 2020-01-06 19:09
> I believe I was using the 2019-07 version. Is that what you're asking?

I was unclear. What version of the SDK are you using? Metafields are supported as of version [2.2.4](https://github.com/Shopify/js-buy-sdk/blob/master/CHANGELOG.md#v224-may-14-2019).

**Comment by tylermcrobert** [comment] 2020-01-06 22:43
I  am using 2.8.1.

**Comment by rebeccajfriedman** [comment] 2020-01-07 22:11
@tylermcrobert I am unable to reproduce your issue. If you provide your myshopify domain, as well as the product you are  expecting to get metafields from, I can look into it.

**Comment by bartoszwrobel** [comment] 2020-01-10 16:10
@tylermcrobert make sure you are using 

`import Client from 'shopify-buy/index.unoptimized.umd';`

instead of 

`import Client from 'shopify-buy';`

**Comment by GaspardC** [comment] 2020-07-05 13:15
Hello 😊

I cannot manage to access custom meta fields, 

I'm using:
`import Client from 'shopify-buy/index.unoptimized.umd';`
and `"shopify-buy": "^2.10.0"`

I believe I've whiltelisted my custom metafield `dateFrom`to make it accessible : 

<img width="848" alt="Capture d’écran 2020-07-05 à 15 08 58" src="https://user-images.githubusercontent.com/9252579/86533478-e35a2700-bed1-11ea-8524-824b9516c5d5.png">

```js
   product.addConnection('metafields', { args: { first: 1 } }, (metafield) => {
                metafield.add('dateFrom')  // NOT working
                metafield.add('createdAt') // working
                metafield.add('namespace') // working
                metafield.add('key')       // working
                metafield.add('value')     // working
            })
```
Could you help me ?  @rebeccajfriedman 

thanks 
Gaspard

**Comment by Caperious** [comment] 2020-11-24 21:22
Has this been resolved? Im facing the same issue.
