### ISSUE TITLE
Any args to order products fetched by collectionId?

### ISSUE THREAD

**Issue by juanlet** [Shopify/js-buy-sdk#649] opened 2019-03-27 08:06 UTC
I'm fetching products of a particular collectionId. Is there any way of adding some parameters to sort that data by PRICE or any other criteria specified in the docs?? I need the data sorted and be able to paginate with the specified sort criteria.

```
const fetchProductsInCollection = async (
  client,
  collectionId
) => {

  try {
    let res = await client.collection.fetchWithProducts(collection.id);
    //sort data received
    return res;
  } catch (error) {
    console.log(error);
    throw new Error(error);
  }
};
```

**Comment by ilievskizoran** [comment] 2019-03-28 05:53
Hey @juanlet
Could you sort after getting all the products?

Not in the best location, but pagination seems to be documented in the [migration guide](https://shopify.github.io/js-buy-sdk/tutorial-MIGRATION_GUIDE.html#paginating-products-on-within-a-collection-) here.

That link shows a snippet using the same collection method above and how you can get the next page, and you could push all the products as you get them to an array and then sort them on the client side.

Hope that helps.

**Comment by jamiemtdwyer** [comment] 2019-03-29 21:39
I'm going to go ahead and close this as it's mostly a duplicate of https://github.com/Shopify/js-buy-sdk/issues/648 – the same solution should apply here.

Please re-open if you feel this was a mistake!

**Closed by jamiemtdwyer** 2019-03-29 21:39 UTC
