### ISSUE TITLE
Fatal error when attempting to create new Checkout object

### ISSUE THREAD

**Issue by joshreeves** [Shopify/js-buy-sdk#572] opened 2018-10-24 19:43 UTC
**Describe the bug**
Starting on or around October 24, the CDN-hosted UMD version of the JS Buy SDK library began returning the following error message when attempting to create a new Checkout object.

`Error: Connections must include the selections "pageInfo { hasNextPage, hasPreviousPage }"` (Screenshot attached below)

**To Reproduce**
```
var client = ShopifyBuy.buildClient({
  domain: 'some-domain.myshopify.com',
  storefrontAccessToken: 'some-access-token'
});
client.checkout.create().then((checkout) => {
  console.log(checkout);
});
```

**Expected behavior**
Expectation is to see a successfully created Checkout object output to the browser's JavaScript console (as it worked on October 23, 2018).

**Environment (please complete the following information):**
 - OS: macOS Sierra
 - Browser: Google Chrome 69.0.3497.100 (Official Build) (64-bit)
 - SDK Version: "latest" (1.9.1 I believe) [Edit: JS file in question reports 1.9.0 as the version]

**Additional context**
Looking at recent work being performed related to `pageInfo`, it appears that perhaps the latest commits by @rebeccajfriedman might be related to this issue.

![image](https://user-images.githubusercontent.com/2991100/47456499-95e36800-d789-11e8-8199-478ffb31abbc.png)

**Bug Report Checklist**
- [*] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [*] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [*] I have provided a detailed description of the bug, including code samples, and/or network data.
- [*] I have provided information about my development environment, including SDK version.

**Comment by joshreeves** [comment] 2018-10-24 19:44
Additionally, I would like to know if there are CDN-hosted copies of previous versions of the SDK. I like the convenience of using the CDN; however, this incident has made me nervous about pointing to the latest.

**Comment by StefanSlehta** [comment] 2018-10-24 19:47
Hi @joshreeves . Can you please verify that the version you're using is `1.9.1` since we did deploy a fix for this issue this morning. Can you also check if the copy is loaded from the server and not from cache (i.e it's not returning a `302`).

**Comment by joshreeves** [comment] 2018-10-24 19:55
@StefanSlehta - thanks for the quick response!

- Cleared all browsing data (cookies and cache)
- Tested in an incognito window in Chrome
- Navigated directly to http://sdks.shopifycdn.com/js-buy-sdk/v1/latest/index.umd.min.js (version reported is 1.9.0)
- Verified the JS being loaded is not from memory
![image](https://user-images.githubusercontent.com/2991100/47457461-07bcb100-d78c-11e8-9fd0-9e50442d04a9.png)

Issue still persists after all of the above.

**Comment by StefanSlehta** [comment] 2018-10-24 20:04
That's very odd, the version loaded should be `1.9.1`, but I'm able to reproduce this when trying the CDN. I'll dig into this a bit. Sorry for the inconvenience!

**Comment by arobbins** [comment] 2018-10-24 20:12
@joshreeves I know you want to use the CDN, but I did verify earlier that the issue has been resolved via the NPM package directly.

**Comment by StefanSlehta** [comment] 2018-10-24 20:20
Hey @joshreeves , can you try using `http://sdks.shopifycdn.com/js-buy-sdk/1.9.1/index.umd.min.js` and see if the issue disappears ?

**Comment by rebeccajfriedman** [comment] 2018-10-24 20:45
We were temporarily experiencing an issue with our CDN. This should be fixed now across all surfaces. Closing this but feel free to reopen if the problem persists.

**Closed by rebeccajfriedman** 2018-10-24 20:45 UTC
